---

- name: Configure python3 on Suse
  hosts: all
  become: true
  tasks:
    - name: Use Python 3 on Suse
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when:
        - ansible_os_family == 'Suse'

    - name: install required python packages on Suse
      ansible.builtin.shell: zypper -n install python-xml python3-rpm python3-PyMySQL
      args:
        removes: /usr/bin/zypper
